Loading data from  data/iwslt-vi-en/train.tok.vi ... 133317 sentences with 2682471 words
Created vocab for  vi of 40000 words
Loading data from  data/iwslt-vi-en/dev.tok.vi ... 1268 sentences with 27470 words
Loading data from  data/iwslt-vi-en/test.tok.vi ... 1553 sentences with 27665 words
Loading data from  data/iwslt-vi-en/train.tok.en ... 133317 sentences with 2706404 words
Created vocab for  en of 40000 words
Loading data from  data/iwslt-vi-en/dev.tok.en ... 1268 sentences with 26728 words
Loading data from  data/iwslt-vi-en/test.tok.en ... 1553 sentences with 27983 words
Max Vocab Size: 40000 , Max Sentence Length 50
Running on  cuda
Using model types: rnn / attn
saving in: models/vi/rnn-attn
Layers: 2 bidirectionl
Hidden Size: 512 , Embd Dim: 512

Begin Training!
epoch 0 : 8m 7s (- 8m 48s) (1000 47%) Loss: 5.7472
epoch 0 : 16m 15s (- 0m 40s) (2000 95%) Loss: 4.6612
epoch 0 : 16m 55s (- 0m 0s) (2083 99%) Loss: 4.3127
Computing VAL
Val loss: 6.4119731187820435
tw:" It read , &quot; When you read this , all five family members will not exist in this world , because we haven &apos;t eaten for the past two weeks . <EOS> "
ow:" In this case , he was a little bit of the he was , he was going to be the same thing , but he was going to be able to do it . <EOS> "
tw:" Porous asphalt , a material that we use now in most of the highways in the Netherlands , it has pores and water can just rain through it , so all the rainwater will flow away to the sides , and you have a road that &apos;s easy to drive on , so no splash water anymore . <EOS> "
ow:" The first is that we &apos;re going to have to and to and to the and the and the and the the , , , , the the , , , , the the the to , and , the the the to , and , the the , , "
tw:" Thank you very much . <EOS> "
ow:" Thank you very much . <EOS> "
tw:" But you have to fight for your <UNK> today . <EOS> "
ow:" What you see is that the most important of the <EOS> "
tw:" So I think these are just a few keys that can help the rest of us to open that door and see the <UNK> that is science and engineering . <EOS> "
ow:" And so I think it &apos;s a very important and a bit of the that we &apos;re going to and the the and the the and the <EOS> "
tw:" Many have been tricked by false promises of a good education , a better job , only to find that they &apos;re forced to work without pay under the threat of violence , and they cannot walk away . <EOS> "
ow:" The people who are going to the the the , , , , , , the the , , , , the the , , , the the , , the the , , the <EOS> "
Val Blue: 0.033972787984925056
epoch 1 : 25m 42s (- 27m 51s) (1000 47%) Loss: 4.2422
epoch 1 : 33m 49s (- 1m 25s) (2000 95%) Loss: 4.0399
epoch 1 : 34m 30s (- 0m 0s) (2083 99%) Loss: 3.9104
Computing VAL
Val loss: 6.049096298217774
tw:" English was so important in South Korea , so I had to start learning my third language . <EOS> "
ow:" Because in the United States , the one who has a very important thing , I , I , , I . my . . <EOS> "
tw:" Because it &apos;s very hollow , all the noise will disappear , so it &apos;s a very silent road . <EOS> "
ow:" Because it &apos;s very , very , , it the the the the to . the . . <EOS> "
tw:" I had moved to New York City for my first job as a writer and editor at Seventeen magazine . <EOS> "
ow:" I went to the United States to the United States , and I was in the . . <EOS> "
tw:" This drug has now been banned for veterinary use in India , and they have taken a stand . <EOS> "
ow:" This is the world &apos;s largest world in the world . <EOS> "
tw:" Thus we are told that &quot; My mercy <UNK> all things . &quot; <EOS> "
ow:" So we call our &quot; <UNK> &quot; to the &quot; &quot; &quot; &quot; <EOS> "
tw:" Thank you . <EOS> "
ow:" Thank you . <EOS> "
tw:" The neurologist &apos;s test is non-invasive . They both use existing infrastructure . <EOS> "
ow:" The other one of the the the not the . . . . . <EOS> "
tw:" When one dollar &apos;s worth of green beans will give you 75 dollars &apos; worth of produce . <EOS> "
ow:" When the average government would get the only one you can get on the top of the <EOS> "
Val Blue: 0.0566387763815389
epoch 2 : 43m 15s (- 46m 53s) (1000 47%) Loss: 3.8325
epoch 2 : 51m 22s (- 2m 9s) (2000 95%) Loss: 3.7699
epoch 2 : 52m 3s (- 0m 1s) (2083 99%) Loss: 3.7769
Computing VAL
Val loss: 5.95749077796936
tw:" These are <UNK> lines of information . <EOS> "
ow:" There are about the other to <EOS> "
tw:" Well you can see where this is going . <EOS> "
ow:" You can see the story . <EOS> "
tw:" And it hit me : One of the most important things we all make are memories . <EOS> "
ow:" And I have to think about the other things that we &apos;ve done is to be <EOS> "
tw:" We can perform low-cost mass recruitment for clinical trials , and we can make <UNK> screening feasible for the first time . <EOS> "
ow:" We can take the <UNK> of the the to , , the , , the , , . <EOS> "
tw:" Government ? Forget about it ! <EOS> "
ow:" Your wish ? Yes . <EOS> "
Val Blue: 0.06898242301033045
epoch 3 : 60m 47s (- 65m 54s) (1000 47%) Loss: 3.6675
epoch 3 : 68m 55s (- 2m 53s) (2000 95%) Loss: 3.6390
epoch 3 : 69m 35s (- 0m 2s) (2083 99%) Loss: 3.7203
Computing VAL
Val loss: 5.73847234249115
tw:" But I only thought that I would be separated from my family for a short time . <EOS> "
ow:" I &apos;m sure , I &apos;m sure , that I to do , I to . . <EOS> "
tw:" And as he grew older , he grew more different , and the differences became more obvious . <EOS> "
ow:" When you &apos;re a , , , , you , . . . <EOS> "
tw:" I promise you there are several people listening to me right now who are currently being abused or who were abused as children or who are <UNK> themselves . <EOS> "
ow:" I &apos;m sure that people in the audience who I &apos;ve heard of the people who I I , , , . . <EOS> "
tw:" Because I &apos;m not in charge of anything , and you could be the editor in chief of American <UNK> or the CEO of H &amp; amp ; M , or the next Steven <UNK> . <EOS> "
ow:" Because you can &apos;t have a problem , you can , you , , you , , , the , , , , , , , , , , , <EOS> "
tw:" In 2009 , I lost someone I loved very much . <EOS> "
ow:" In the &apos; 70s , I was a child . <EOS> "
tw:" You can give somebody an idea . <EOS> "
ow:" You can give a couple of questions . <EOS> "
tw:" Who is going to invent the technology for the green revolution ? Universities ? Forget about it ! <EOS> "
ow:" What does that mean by the way the system ? The &quot; ? ? : ? ? ? . <EOS> "
Val Blue: 0.07152381733415544
epoch 4 : 78m 18s (- 84m 53s) (1000 47%) Loss: 3.5574
epoch 4 : 86m 26s (- 3m 37s) (2000 95%) Loss: 3.5597
epoch 4 : 87m 6s (- 0m 2s) (2083 99%) Loss: 3.4435
Computing VAL
Val loss: 5.841682481765747
tw:" Then you can have a lot of splash water in the asphalt . <EOS> "
ow:" And you can go to water . <EOS> "
tw:" You know , it &apos;s remarkable how universal the gesture is of handing your camera to a total stranger . <EOS> "
ow:" You know , the word is the word that you have to , the the . . <EOS> "
tw:" And I always just say , &quot; Oh , I was scouted , &quot; but that means nothing . <EOS> "
ow:" And I said , &quot; Well , I &apos;m doing this , but it &apos;s not something that &apos;s true . <EOS> "
tw:" No one knows what the hell we do . <EOS> "
ow:" Nobody knows what we &apos;re doing is the problem . <EOS> "
tw:" Thank you . <EOS> "
ow:" Thank you . <EOS> "
Val Blue: 0.07750353831053065
epoch 5 : 95m 51s (- 103m 54s) (1000 47%) Loss: 3.4899
epoch 5 : 103m 59s (- 4m 22s) (2000 95%) Loss: 3.5066
epoch 5 : 104m 39s (- 0m 3s) (2083 99%) Loss: 3.4455
Computing VAL
Val loss: 5.832679319381714
tw:" In school , we spent a lot of time studying the history of Kim <UNK> , but we never learned much about the outside world , except that America , South Korea , Japan are the enemies . <EOS> "
ow:" In our schools , we spend a lot of time with our future school , our own , but we don &apos;t have a lot of of of of we , <EOS> "
tw:" We victims need everyone . <EOS> "
ow:" We have the ability to help all of these people . <EOS> "
tw:" It was cozy in winter but extremely hot in summer . <EOS> "
ow:" It &apos;s a bit of a in . It &apos;s in <EOS> "
tw:" I dream big , but my family dreams even bigger for me . <EOS> "
ow:" I mean , I &apos;m sure , but I was my family to my . <EOS> "
tw:" But the second answer , and what I really want to say to these little girls is , &quot; Why ? <EOS> "
ow:" But the next question I want to talk to you about is that the girl are &quot; or why ? &quot; <EOS> "
tw:" Two of the most valuable things we have are time and our relationships with other people . <EOS> "
ow:" The other important thing is that we have is a and a . <EOS> "
tw:" In our age of increasing distractions , it &apos;s more important than ever to find ways to maintain perspective and remember that life is brief and tender . <EOS> "
ow:" In our own <UNK> , this is , perhaps more important than ever , and when the life is and is . <EOS> "
tw:" I was trying to trick the lions &#91; into thinking &#93; that I was standing near the cowshed . <EOS> "
ow:" I decided to take a to the to I I I I I . I I . I . . <EOS> "
tw:" That &apos;s all this project was about , about restoring those little bits of humanity , giving someone that connection back . <EOS> "
ow:" That &apos;s how the brain works , the the and a and a <EOS> "
tw:" <UNK> exists everywhere , nearly , in the world , and yet it is illegal everywhere in the world . <EOS> "
ow:" It &apos;s always the same thing in the world , it &apos;s it . in <EOS> "
tw:" Some don &apos;t even know they &apos;re enslaved , people working 16 , 17 hours a day without any pay , because this has been the case all their lives . <EOS> "
ow:" Some people don &apos;t know what they &apos;re doing is they &apos;re not , but they &apos;re they , and they &apos;re , they &apos;re they &apos;re like , <EOS> "
tw:" My interpreter told me their stories . <EOS> "
ow:" My own voice . <EOS> "
Val Blue: 0.08598578320495769
epoch 6 : 113m 22s (- 122m 54s) (1000 47%) Loss: 3.4088
epoch 6 : 121m 30s (- 5m 6s) (2000 95%) Loss: 3.4594
epoch 6 : 122m 10s (- 0m 3s) (2083 99%) Loss: 3.4008
Computing VAL
Val loss: 5.885663485527038
Epoch     6: reducing learning rate of group 0 to 2.5000e-02.
Epoch     6: reducing learning rate of group 0 to 2.5000e-02.
tw:" Today I use a microwave because I cannot take the big induction machine here onstage . <EOS> "
ow:" I &apos;m using a little bit because I &apos;m not going to put a camera on the back of the night . <EOS> "
tw:" Even though he held those loaded guns to my head , pushed me down stairs , threatened to kill our dog , pulled the key out of the car ignition as I drove down the highway , poured coffee <UNK> on my head as I dressed for a job interview , I never once thought of myself as a battered wife . <EOS> "
ow:" Even though he had been my wife , I took my hand , my wife , my car , my car , my car , my legs , my legs , my legs , his <UNK> , my grandfather , and I was walking around the door to the night "
tw:" There are the New World vultures that are mainly found in the Americas , like the <UNK> and the <UNK> , and then the Old World vultures , where we have 16 species . From these 16 , 11 of them are facing a high risk of extinction . <EOS> "
ow:" The Tasmanian devil shows that the majority of the year , and the , and , , , , , , , , , , , , , , , , , . , . , <EOS> "
tw:" This one was taken just weeks after 9 / 11 , and I found myself trying to explain what had happened that day in ways a five-year-old could understand . <EOS> "
ow:" This was a little bit ago at the summer of 2009 , and I was trying to figure out what happened to the point of the 15 years . <EOS> "
tw:" Our society , shaped by a revolutionary mindset , became more polarized and has driven away from the ideals and the principles -- freedom , dignity , social justice -- that we first held . <EOS> "
ow:" Our business , our work of compassion , and we &apos;re using the same , we , , , and , , , , , , , , , , , , , , , , , , , , . the . <EOS> "
tw:" I grew up there . I raised my sons there . <EOS> "
ow:" I grew up . I gave my children in there . <EOS> "
tw:" The lady who brought us these photos was lucky , as far as the photos go . <EOS> "
ow:" The women are able to teach these pictures , and when they can be . <EOS> "
tw:" Some don &apos;t even know they &apos;re enslaved , people working 16 , 17 hours a day without any pay , because this has been the case all their lives . <EOS> "
ow:" Some people don &apos;t know who they &apos;re growing up , but they &apos;re not going , and they , they , they , they . <EOS> "
Val Blue: 0.08371314289466822
epoch 7 : 130m 52s (- 141m 52s) (1000 47%) Loss: 3.3011
epoch 7 : 138m 43s (- 5m 49s) (2000 95%) Loss: 3.2448
epoch 7 : 139m 22s (- 0m 4s) (2083 99%) Loss: 3.1642
Computing VAL
Val loss: 5.769172883033752
tw:" I &apos;ve spent most of my career working for Fortune 500 companies including Johnson &amp; amp ; Johnson , Leo <UNK> and The Washington Post . <EOS> "
ow:" I &apos;ve been the of since the to of the the of the of the of the of the of the the of , , , , , , , , , , , , , , . . <EOS> "
tw:" I was able to leave , because of one final , <UNK> beating that broke through my denial . <EOS> "
ow:" I could go , because I was a I the I I I . . I <EOS> "
tw:" Who sends whom a text message ? <EOS> "
ow:" Who killed the kids to the who ? <EOS> "
tw:" So I want to encourage everyone today to get in the shot , and don &apos;t hesitate to go up to someone and ask , &quot; Will you take our picture ? &quot; <EOS> "
ow:" So I &apos;m going to share all of you as you &apos;re in the , , and , , , , , , , , , , , , , , , , you ? &quot; to . . . . . . . . <EOS> "
tw:" Okay , so the next question people always ask me is , &quot; Do you get free stuff ? &quot; <EOS> "
ow:" The next question I had was asked to ask , &quot; How many people are you going to need to be ? &quot; <EOS> "
tw:" I couldn &apos;t offer them any direct help . <EOS> "
ow:" I couldn &apos;t help them . <EOS> "
Val Blue: 0.09066840956024348
epoch 8 : 147m 48s (- 160m 13s) (1000 47%) Loss: 3.1632
epoch 8 : 155m 38s (- 6m 32s) (2000 95%) Loss: 3.1543
epoch 8 : 156m 17s (- 0m 4s) (2083 99%) Loss: 3.1070
Computing VAL
Val loss: 5.915235686302185
tw:" He did this especially at the beginning by <UNK> me . <EOS> "
ow:" He made this thing about this , and I started to <EOS> "
tw:" We &apos;re talking to them about appreciating vultures , about the need from within to appreciate these wonderful creatures and the services that they provide . <EOS> "
ow:" We &apos;re talking about them as the experts of the and , and , the and , , , they <EOS> "
tw:" We have the opportunity to start to search for the early <UNK> of the disease before it &apos;s too late . <EOS> "
ow:" We have a chance to start looking at the <UNK> of the the of , the <EOS> "
tw:" The lights flash and trick the lions into thinking I was walking around the cowshed , but I was sleeping in my bed . <EOS> "
ow:" The lights go down and the <UNK> , and they , they , I , , they , they , I I . <EOS> "
tw:" But this time , I would see the skeletons hidden in the closet . <EOS> "
ow:" But at the same time , I wanted to see that the actual was <UNK> . <EOS> "
Val Blue: 0.0988278332012031
epoch 9 : 164m 43s (- 178m 34s) (1000 47%) Loss: 3.1144
epoch 9 : 172m 34s (- 7m 14s) (2000 95%) Loss: 3.1334
epoch 9 : 173m 13s (- 0m 4s) (2083 99%) Loss: 3.1003
Computing VAL
Val loss: 5.779599285125732
Epoch     9: reducing learning rate of group 0 to 2.5000e-03.
Epoch     9: reducing learning rate of group 0 to 2.5000e-03.
tw:" We would cover our books in grocery bags so it would seem we were just out shopping . <EOS> "
ow:" We were told in the <UNK> that we all wanted to think we were going to <EOS> "
tw:" Take your science , subtract your bullet points and your jargon , divide by relevance , meaning share what &apos;s relevant to the audience , and multiply it by the passion that you have for this incredible work that you &apos;re doing , and that is going to equal incredible interactions that are full of understanding . <EOS> "
ow:" So , for &quot; <UNK> &quot; with the &quot; &quot; and &quot; and , , , , , , , , , , , , , , , , , , , , , , , , to , , , , &quot; , &quot; <EOS> "
tw:" Now , I live in New Orleans , and I am in love with New Orleans . <EOS> "
ow:" Now , I live in New Zealand , and I &apos;m the French <UNK> . <EOS> "
tw:" And I &apos;d like to share a few things that people wrote on this wall . <EOS> "
ow:" And I want to share some of the things that people are reading to the <EOS> "
tw:" We &apos;re pale , gray creatures . <EOS> "
ow:" We &apos;re the <UNK> . <EOS> "
tw:" I couldn &apos;t give them money , nothing . <EOS> "
ow:" I didn &apos;t have them money , no . <EOS> "
Val Blue: 0.09872410363863018
epoch 10 : 181m 39s (- 196m 54s) (1000 47%) Loss: 3.1005
epoch 10 : 189m 29s (- 7m 57s) (2000 95%) Loss: 3.0654
epoch 10 : 190m 8s (- 0m 5s) (2083 99%) Loss: 3.0048
Computing VAL
Val loss: 5.84646852016449
tw:" But most people don &apos;t agree . <EOS> "
ow:" But most people don &apos;t agree . <EOS> "
tw:" I was raised in a country that has been destroyed by decades of war . <EOS> "
ow:" I was growing up in a country where the village was still in the case of war . <EOS> "
tw:" Afghanistan looks so different from here in America . <EOS> "
ow:" The other way around the world are the . . <EOS> "
tw:" And here you can see , like 10 thousands of people went out on the streets of Berlin and said , &quot; Freedom , not fear . &quot; <EOS> "
ow:" And you can see here , like the <UNK> people who are in the the and and and and and and and and , , &quot; &quot; , , , <EOS> "
tw:" These heels are very uncomfortable , so good thing I wasn &apos;t going to wear them . <EOS> "
ow:" This is a very , , , , , , , I to . . . <EOS> "
tw:" And this is a legacy that was built for me , and it &apos;s a legacy that I &apos;ve been <UNK> out on . <EOS> "
ow:" This is the kind of thing that I &apos;m working on and is the I I I I <EOS> "
tw:" And when we do this , who knows ? <EOS> "
ow:" And when we do that , what do you know ? <EOS> "
tw:" Can you imagine a community of 400,000 people , the intelligence and the passion ? <EOS> "
ow:" Could it be that possible , for many communities , for the laws of compassion and the mind ? <EOS> "
tw:" Government ? Forget about it ! <EOS> "
ow:" Life ? &quot; <EOS> "
tw:" For her , despite all of this , those photos were the perfect gift back to him , something he could look at again , something he remembered from before that wasn &apos;t still scarred from that day in March when absolutely everything else in his life had changed or been destroyed . <EOS> "
ow:" For him , after all , this picture is a beautiful thing , &quot; for the next one , is the answer to the , , something that , , , , , , the , , the , , the , the , the the , of <EOS> "
Val Blue: 0.10066014314303888
epoch 11 : 198m 34s (- 215m 15s) (1000 47%) Loss: 3.0710
epoch 11 : 206m 25s (- 8m 40s) (2000 95%) Loss: 3.0686
epoch 11 : 207m 3s (- 0m 5s) (2083 99%) Loss: 3.0848
Computing VAL
Val loss: 5.83702323436737
tw:" And I see their parents and their fathers who , like my own , advocate for them , despite and even in the face of daunting opposition . <EOS> "
ow:" And I found them and my father , my father , who , and , and even when they were , they were . <EOS> "
tw:" Well you can see where this is going . <EOS> "
ow:" You can see what &apos;s going on . <EOS> "
tw:" So Max , by taking all these samples of , let &apos;s say , 10,000 people , you &apos;ll be able to tell who &apos;s healthy and who &apos;s not ? <EOS> "
ow:" Tom <UNK> : So , by the way , all the way all the way to the all the to to to the , , ? , ? ? ? ? ? <EOS> "
tw:" You have to create a new profession . <EOS> "
ow:" You have to create a new kind of new project . <EOS> "
tw:" Like the others , I wear a flickering , cheap flashlight tied to my head with this elastic , tattered band , and I can barely make out the slick tree limbs holding up the walls of the <UNK> square hole dropping hundreds of feet into the earth . <EOS> "
ow:" As a man , I took a <UNK> , I , , it , , , the , , , , the of , , the of , , the of , the the of , the the the the the <EOS> "
tw:" I saw what seemed to be a family fishing on a boat , two older brothers , some younger kids , makes sense right ? <EOS> "
ow:" I see it as a child with a hundred and a half , and a few , a couple of of , <EOS> "
Val Blue: 0.10208170735892641
epoch 12 : 215m 29s (- 233m 35s) (1000 47%) Loss: 3.0588
epoch 12 : 223m 20s (- 9m 22s) (2000 95%) Loss: 3.0800
epoch 12 : 223m 59s (- 0m 6s) (2083 99%) Loss: 2.9591
Computing VAL
Val loss: 5.853832578659057
Epoch    12: reducing learning rate of group 0 to 2.5000e-04.
Epoch    12: reducing learning rate of group 0 to 2.5000e-04.
tw:" It happened twice more on the <UNK> . <EOS> "
ow:" It &apos;s been a few days in the early &apos; 90s . <EOS> "
tw:" Raw data . <EOS> "
ow:" The information is <UNK> . <EOS> "
tw:" But unfortunately I have to inform you that in 2007 , a very inspired NYU Ph.D. student counted all the models on the runway , every single one that was hired , and of the <UNK> models that were hired , only 27 , or less than four percent , were non-white . <EOS> "
ow:" But unfortunately , I &apos;m not talking to you , in the , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , . , "
tw:" So you &apos;re 86 percent accurate right now ? <EOS> "
ow:" So what is the percentage of the war ? <EOS> "
Val Blue: 0.10326402572378898
epoch 13 : 232m 25s (- 251m 56s) (1000 47%) Loss: 3.0694
epoch 13 : 240m 16s (- 10m 5s) (2000 95%) Loss: 3.0711
epoch 13 : 240m 54s (- 0m 6s) (2083 99%) Loss: 2.9506
Computing VAL
Val loss: 5.846532201766967
tw:" I &apos;ve been so lucky , received so much help and inspiration in my life , so I want to help give aspiring North Koreans a chance to prosper with international support . <EOS> "
ow:" I was so fortunate that I was also very interested in and had to do my life , so I wanted to be able to take my life to help me to go to the city to me to the . . <EOS> "
tw:" And in fact , because their minds don &apos;t fit into society &apos;s version of normal , they &apos;re often bypassed and misunderstood . <EOS> "
ow:" And so because my belief is not to look at the relationship between the poor , the people who are always and <EOS> "
tw:" And those things are true , but they &apos;re only one half of the story , because the thing that we never say on camera , that I have never said on camera , is , &quot; I am insecure . &quot; <EOS> "
ow:" And that &apos;s exactly what , of course , that we have never been talking about the , , , , , I , I , I , I , to &quot; I &quot; I &quot; I &quot; I &quot; I . . I <EOS> "
tw:" We see vocal tremor , weakness and rigidity . <EOS> "
ow:" We see the <UNK> , the and . . <EOS> "
tw:" You can give somebody an idea . <EOS> "
ow:" You can ask someone else &apos;s idea . <EOS> "
Val Blue: 0.1022193246458744
epoch 14 : 249m 20s (- 270m 17s) (1000 47%) Loss: 3.0572
epoch 14 : 257m 11s (- 10m 48s) (2000 95%) Loss: 3.0781
epoch 14 : 257m 50s (- 0m 7s) (2083 99%) Loss: 3.0708
Computing VAL
Val loss: 5.848996710777283
tw:" I could have never imagined that it would take 14 years to live together . <EOS> "
ow:" I never thought I would have been around for about five years . <EOS> "
tw:" We made it all the way to the border of Laos , but I had to spend almost all my money to bribe the border guards in Laos . <EOS> "
ow:" And we went from a <UNK> , and I I , , , , to , , to the . . . . . <EOS> "
tw:" Were we being followed ? <EOS> "
ow:" Are I ever get a ? <EOS> "
tw:" I don &apos;t know about you , but aside from these 15 shots , I &apos;m not in many of the family photos . <EOS> "
ow:" I don &apos;t know about you , but I think it &apos;s a of a to . , . . . . <EOS> "
tw:" That was awkward . <EOS> "
ow:" It &apos;s a real . <EOS> "
tw:" This is one of the cows which was killed at night , and I just woke up in the morning and I found it dead , and I felt so bad , because it was the only bull we had . <EOS> "
ow:" This is one of the <UNK> that &apos;s in the the , , , and , , , , , , , , , , , , , I , . . . <EOS> "
tw:" Many have been tricked by false promises of a good education , a better job , only to find that they &apos;re forced to work without pay under the threat of violence , and they cannot walk away . <EOS> "
ow:" Many people are still in trouble with the moral business , the opportunity to get to work , not only to see the , but to . , <EOS> "
Val Blue: 0.10192456743027743
epoch 15 : 266m 16s (- 288m 38s) (1000 47%) Loss: 3.0536
epoch 15 : 274m 6s (- 11m 30s) (2000 95%) Loss: 3.0878
epoch 15 : 274m 45s (- 0m 7s) (2083 99%) Loss: 3.0516
Computing VAL
Val loss: 5.848076796531677
Epoch    15: reducing learning rate of group 0 to 2.5000e-05.
Epoch    15: reducing learning rate of group 0 to 2.5000e-05.
tw:" I started studying for the university entrance exam . <EOS> "
ow:" And in the beginning , to try to try and learn to do this . <EOS> "
tw:" He doesn &apos;t remember if he stole my chocolate bar , but he remembers the year of release for every song on my iPod , conversations we had when he was four , <UNK> on my arm on the first ever episode of <UNK> , and Lady Gaga &apos;s birthday . <EOS> "
ow:" You don &apos;t remember that my father &apos;s dog &apos;s dog , my wife , and I remember the first time I was sitting in my house , , , , , , , , , , , , , , , , , , , . , . . "
tw:" Don &apos;t just tell me that you study <UNK> , but tell me that you study <UNK> , which is the <UNK> structure of our bones because it &apos;s important to understanding and treating <UNK> . <EOS> "
ow:" Don &apos;t just say that we &apos;ve created the device , so you tell us how to use the machine , it &apos;s like the the that the the the the the and and . . <EOS> "
tw:" So you &apos;re 86 percent accurate right now ? <EOS> "
ow:" So what is the percentage of the war ? <EOS> "
tw:" It &apos;s much better than that . <EOS> "
ow:" More than that . <EOS> "
tw:" If you want to meet with me , come to the garden with your shovel so we can plant some shit . <EOS> "
ow:" If you want to see me , go to the next side of your hand and we &apos;ll be able to add more . <EOS> "
tw:" We are at the end of the first industrial revolution -- <UNK> fossil fuels , manufacturing -- and all of a sudden , we have systems which are not sustainable . <EOS> "
ow:" We are at the end of the first of the the the the the , , , , , the , , , , , , , , , , , , , , , , , , . . <EOS> "
tw:" This person has never been born . <EOS> "
ow:" This guy has never been born . <EOS> "
tw:" So that evening , I just reached out on Facebook and asked a few of them , and by morning the response had been so overwhelming and so positive , I knew we had to give it a go . <EOS> "
ow:" So at that point , I took my eyes and I asked some people , and then I went to a big deal , I know how to go . <EOS> "
Val Blue: 0.10271733453679731
epoch 16 : 283m 11s (- 306m 59s) (1000 47%) Loss: 3.1096
epoch 16 : 291m 2s (- 12m 13s) (2000 95%) Loss: 3.0505
epoch 16 : 291m 41s (- 0m 8s) (2083 99%) Loss: 3.0229
Computing VAL
Val loss: 5.849928450584412
tw:" I did everything to get my family to freedom , and we came so close , but my family was thrown in jail just a short distance from the South Korean embassy . <EOS> "
ow:" I &apos;ve done everything to help my family &apos;s to fight for the sake of the country , and I &apos;m also the moment that we &apos;re still waiting for me to be when we &apos;re going to have a <UNK> , and , to <EOS> "
tw:" So why are vultures important ? First of all , they provide vital ecological services . They clean up . <EOS> "
ow:" So , why is the best way ? They learn to be smart , they &apos;re <UNK> . <EOS> "
tw:" The exciting thing is that I see students at my school with ambition grabbing at opportunity . <EOS> "
ow:" I was so surprised to see my students with the help of my students with the help of this . <EOS> "
tw:" So I figured that the problem is the solution . <EOS> "
ow:" I realized that the problem is the solution . <EOS> "
tw:" Because , you see , at least we fed the <UNK> . <EOS> "
ow:" Because , as you see , there &apos;s only a few of the dead . <EOS> "
Val Blue: 0.1028847916241912
epoch 17 : 300m 6s (- 325m 19s) (1000 47%) Loss: 3.0508
epoch 17 : 307m 57s (- 12m 56s) (2000 95%) Loss: 3.0958
epoch 17 : 308m 36s (- 0m 8s) (2083 99%) Loss: 2.9920
Computing VAL
Val loss: 5.850634431838989
tw:" And he also created a magical atmosphere of trust between us by <UNK> his secret , which was that , as a very young boy starting at age four , he had been <UNK> and repeatedly physically abused by his stepfather , and the abuse had gotten so bad that he had had to drop out of school in eighth grade , even though he was very smart , and he &apos;d spent almost 20 years rebuilding his life . <EOS> "
ow:" And he also created the <UNK> of the the his most of his , , , , , , , , , , , , , his , , his , , , , his , , , his . . . his <EOS> "
tw:" And here you can see , like 10 thousands of people went out on the streets of Berlin and said , &quot; Freedom , not fear . &quot; <EOS> "
ow:" And you can see here , like the <UNK> people who are in the the and and and and and and and and , , , . &quot; <EOS> "
tw:" Sex trafficking is what we often think of when we hear the word slavery , and because of this worldwide awareness , I was warned that it would be difficult for me to work safely within this particular industry . <EOS> "
ow:" We think of love as a child , as a result of that , and I think , is to be , to , to , , , , , the <EOS> "
Val Blue: 0.10285917415254896
epoch 18 : 317m 2s (- 343m 40s) (1000 47%) Loss: 3.0950
epoch 18 : 324m 53s (- 13m 38s) (2000 95%) Loss: 3.0518
epoch 18 : 325m 32s (- 0m 9s) (2083 99%) Loss: 2.9928
Computing VAL
Val loss: 5.851425266265869
Epoch    18: reducing learning rate of group 0 to 2.5000e-06.
Epoch    18: reducing learning rate of group 0 to 2.5000e-06.
tw:" But I will do a trial . <EOS> "
ow:" But let me just show you . <EOS> "
tw:" You know ? You can be anything . <EOS> "
ow:" You know ? You can &apos;t . <EOS> "
tw:" Thank you . <EOS> "
ow:" Thank you . <EOS> "
tw:" The internal combustion engine is not sustainable . <EOS> "
ow:" The air is not sustainable . <EOS> "
Val Blue: 0.10273634210107328
epoch 19 : 333m 57s (- 362m 1s) (1000 47%) Loss: 3.0799
epoch 19 : 341m 48s (- 14m 21s) (2000 95%) Loss: 3.0577
epoch 19 : 342m 27s (- 0m 9s) (2083 99%) Loss: 2.9940
Computing VAL
Val loss: 5.851429438591003
tw:" So I was living in constant fear that my identity could be revealed , and I would be <UNK> to a horrible fate back in North Korea . <EOS> "
ow:" I still live in a strange fear of what I believe to be , and I &apos;m going to share the lives of the in the in <EOS> "
tw:" &quot; I &apos;m helping the North Korean people . &quot; <EOS> "
ow:" &quot; I &apos;m going to save the North Pole . &quot; <EOS> "
tw:" We started dating , and he loved everything about me , that I was smart , that I &apos;d gone to Harvard , that I was passionate about helping teenage girls , and my job . <EOS> "
ow:" We started , and he and his wife , and I was like , and I , , and and , and and and and and and . . . . . . . . <EOS> "
tw:" You see , I was six when the Taliban took over Afghanistan and made it illegal for girls to go to school . <EOS> "
ow:" You know , the police from the &apos; 70s when I was six months old and I met my parents . <EOS> "
tw:" But today I will talk about me and my mobile phone , and how it changed my life . <EOS> "
ow:" But today I &apos;m going to talk about my own and , the how it changed . <EOS> "
tw:" Well , hopefully not as awkward as that picture . <EOS> "
ow:" In fact , the reason it &apos;s not really that easy to see this picture . <EOS> "
tw:" I am on this stage because I am a pretty , white woman , and in my industry we call that a sexy girl . <EOS> "
ow:" I &apos;m standing on this stage because I &apos;m a little bit , a woman , and in a sense , we called it a . . <EOS> "
tw:" Well , for the past few centuries we have defined beauty not just as health and youth and symmetry that we &apos;re biologically programmed to admire , but also as tall , slender figures , and <UNK> and white skin . <EOS> "
ow:" In the past decade , we &apos;ve been able to not the of &apos;t be , and , and and , , , , and , , , and , and and and and and and and and and and . and <EOS> "
tw:" Who is going to invent the technology for the green revolution ? Universities ? Forget about it ! <EOS> "
ow:" What is the key to the revolution ? The Chinese government ? No . <EOS> "
Val Blue: 0.10273634210107328
epoch 20 : 350m 53s (- 380m 21s) (1000 47%) Loss: 3.0856
epoch 20 : 358m 44s (- 15m 4s) (2000 95%) Loss: 3.0544
epoch 20 : 359m 22s (- 0m 10s) (2083 99%) Loss: 2.9477
Computing VAL
Val loss: 5.85142879486084
tw:" Even though I was really fortunate to get out , many other North Koreans have not been so lucky . <EOS> "
ow:" And I was very lucky to get the to because I was so much more than my own . my <EOS> "
tw:" I &apos;m not a psychiatrist , a social worker or an expert in domestic violence . <EOS> "
ow:" I &apos;m not a doctor , not a scientist who &apos;s social media or a scientist to the family . <EOS> "
tw:" My family believes in me . <EOS> "
ow:" My family is very . <EOS> "
tw:" They said , we don &apos;t want this data retention . <EOS> "
ow:" They said , we don &apos;t want to use the information . <EOS> "
tw:" For four decades Gaddafi &apos;s tyrannical regime destroyed the infrastructure as well as the culture and the moral fabric of Libyan society . <EOS> "
ow:" Over the next four years , the <UNK> of the <UNK> the , the , , and , of . of . . <EOS> "
tw:" And I &apos;m going to answer the questions that people always ask me , but with an honest twist . <EOS> "
ow:" And I &apos;ll ask questions that people are asking me to ask , but with the truth . <EOS> "
tw:" Her name was Joan , and she was a mother to me , and her death was sudden and unexpected . <EOS> "
ow:" His name is <UNK> , and she &apos;s a mother who &apos;s and and and and and and . . <EOS> "
tw:" It &apos;s my gospel , when I &apos;m telling people , grow your own food . <EOS> "
ow:" That &apos;s my favorite , when I told people , to protect my food . <EOS> "
tw:" And I think this is why the Nairobi National Park lions are few . <EOS> "
ow:" And I think this is the reason that the the in in the <EOS> "
tw:" <UNK> , I treat anybody from a different culture as if they were my children . &quot; I love you so much . &quot; <EOS> "
ow:" &quot; <UNK> , I am with people &apos;s friends and the data , the , they they me . &quot; I love them . &quot; <EOS> "
tw:" Thank you . <EOS> "
ow:" Thank you . <EOS> "
tw:" We &apos;re pale , gray creatures . <EOS> "
ow:" We &apos;re the <UNK> . <EOS> "
Val Blue: 0.10273634210107328
epoch 21 : 367m 48s (- 398m 42s) (1000 47%) Loss: 3.0562
epoch 21 : 375m 39s (- 15m 46s) (2000 95%) Loss: 3.0464
epoch 21 : 376m 18s (- 0m 10s) (2083 99%) Loss: 3.0494
Computing VAL
Val loss: 5.85143518447876
Epoch    21: reducing learning rate of group 0 to 2.5000e-07.
Epoch    21: reducing learning rate of group 0 to 2.5000e-07.
tw:" Since my family couldn &apos;t understand Chinese , I thought my family was going to be arrested . <EOS> "
ow:" Because my family didn &apos;t believe that corruption , I thought they would be saved . <EOS> "
tw:" You can be extraordinary . <EOS> "
ow:" You can be surprised . <EOS> "
tw:" So actually , I was in very good company . <EOS> "
ow:" So , I actually was in a business business . <EOS> "
tw:" Our society , shaped by a revolutionary mindset , became more polarized and has driven away from the ideals and the principles -- freedom , dignity , social justice -- that we first held . <EOS> "
ow:" Our lives , our <UNK> , are the , , , and , , and and , , , , , , , , , , , , , . our . our . <EOS> "
tw:" So with help from old and new friends , I turned the side of this abandoned house into a giant chalkboard and <UNK> it with a <UNK> sentence : &quot; Before I die , I want to ... &quot; So anyone walking by can pick up a piece of chalk , reflect on their lives , and share their personal aspirations in public space . <EOS> "
ow:" So with the help of my friends and new , I put a piece of the building of this building into a very , very <UNK> , a , a this a a &quot; -- &quot; -- -- I I , I , , &quot; -- &apos;t . &quot; <EOS> "
tw:" If they grow tomatoes , they eat tomatoes . <EOS> "
ow:" If they &apos;re <UNK> , they will die . <EOS> "
tw:" It &apos;s very easy to do more damage to those damaged photos . <EOS> "
ow:" It &apos;s more than the other these . <EOS> "
Val Blue: 0.10273634210107328
epoch 22 : 384m 44s (- 417m 3s) (1000 47%) Loss: 3.0571
epoch 22 : 392m 34s (- 16m 29s) (2000 95%) Loss: 3.0337
epoch 22 : 393m 13s (- 0m 11s) (2083 99%) Loss: 3.0368
Computing VAL
Val loss: 5.851435685157776
tw:" In South Asia , in countries like India and Pakistan , four species of vultures are listed as critically endangered , which means they have less than 10 or 15 years to go extinct , and the reason is because they are falling prey by consuming livestock that has been treated with a <UNK> drug like <UNK> . <EOS> "
ow:" In the West , countries like India and Brazil , the two great <UNK> are in the middle of the , , , , , , , , , , , , , , , , , , , , , , , , , , , , , <EOS> "
tw:" So I decided to start a lawsuit against them , because I wanted to have this information . <EOS> "
ow:" And I decided to put my <UNK> in the , , I wanted to do it . <EOS> "
tw:" Almost 200 organizations were established in Benghazi during and immediately after the fall of Gaddafi -- almost 300 in <UNK> . <EOS> "
ow:" The poor million people are born in the in the last years since and then , and they were <UNK> -- and they were killed in the . <EOS> "
tw:" The next question people always ask me is , &quot; Can I be a model when I grow up ? &quot; <EOS> "
ow:" The next question is , &quot; Do you get me when you &apos;re not a <EOS> "
tw:" Because I &apos;m not in charge of anything , and you could be the editor in chief of American <UNK> or the CEO of H &amp; amp ; M , or the next Steven <UNK> . <EOS> "
ow:" Because he didn &apos;t have any money , he could be the first <UNK> at the University of the University of the in the in the United States or the . . . . . <EOS> "
tw:" Hopefully less awkward than that one in the middle . <EOS> "
ow:" And it &apos;s a little bit more than than one of the images . <EOS> "
tw:" We make skinny models <UNK> , perfect skin more perfect , and the impossible possible , and we get criticized in the press all the time , but some of us are actually talented artists with years of experience and a real appreciation for images and photography . <EOS> "
ow:" We put a little bit more , and we , we , and we and , and , and , and , and , and , and , and , and , and , and and and and and and and and and . . . . . . <EOS> "
Val Blue: 0.10273634210107328
epoch 23 : 401m 39s (- 435m 23s) (1000 47%) Loss: 3.0579
epoch 23 : 409m 29s (- 17m 11s) (2000 95%) Loss: 3.0489
epoch 23 : 410m 8s (- 0m 11s) (2083 99%) Loss: 2.9367
Computing VAL
Val loss: 5.851435327529908
tw:" It read , &quot; When you read this , all five family members will not exist in this world , because we haven &apos;t eaten for the past two weeks . <EOS> "
ow:" And then there &apos;s a quote : when she read this thing every year for three days , you know , they &apos;re not going to die in the next two weeks . <EOS> "
tw:" We &apos;re working with local communities . <EOS> "
ow:" We &apos;re working with social media . <EOS> "
tw:" Raw data . <EOS> "
ow:" The information is <UNK> . <EOS> "
tw:" Our shared spaces can better reflect what matters to us as individuals and as a community , and with more ways to share our hopes , fears and stories , the people around us can not only help us make better places , they can help us lead better lives . <EOS> "
ow:" The whole world that we have more than we are more than , we , and , , and , and , and , and , and and and and and and and , and we and and and and and and and and and and and and and and "
Val Blue: 0.10273634210107328
epoch 24 : 418m 34s (- 453m 44s) (1000 47%) Loss: 3.0888
epoch 24 : 426m 25s (- 17m 54s) (2000 95%) Loss: 3.0402
epoch 24 : 427m 4s (- 0m 12s) (2083 99%) Loss: 3.1098
Computing VAL
Val loss: 5.851435327529908
Epoch    24: reducing learning rate of group 0 to 2.5000e-08.
Epoch    24: reducing learning rate of group 0 to 2.5000e-08.
tw:" We have eight species of vultures that occur in Kenya , of which six are highly threatened with extinction . <EOS> "
ow:" We have about four of them in the in in the in the in in the in the in in the in the in the in . . <EOS> "
tw:" We &apos;re trying to determine their basic ecology , and see where they go . <EOS> "
ow:" We &apos;re trying to get the right ones , and in the the where they &apos;re <EOS> "
tw:" Hi . This is my mobile phone . <EOS> "
ow:" Hello . This is my phone . <EOS> "
tw:" So I set up everything . <EOS> "
ow:" And I put everything together . <EOS> "
tw:" It &apos;s difficult to witness something so overwhelming . <EOS> "
ow:" <UNK> are very , very <EOS> "
Val Blue: 0.10273634210107328
epoch 25 : 435m 30s (- 472m 5s) (1000 47%) Loss: 3.0780
epoch 25 : 443m 21s (- 18m 37s) (2000 95%) Loss: 3.0431
epoch 25 : 443m 59s (- 0m 12s) (2083 99%) Loss: 3.0231
Computing VAL
Val loss: 5.851435422897339
tw:" I had my first apartment , my first little green American Express card , and I had a very big secret . <EOS> "
ow:" When I first got my home , my heart &apos;s heart rate was my home , and I had a big deal . <EOS> "
tw:" Five days later , the ten bruises on my neck had just faded , and I put on my mother &apos;s wedding dress , and I married him . <EOS> "
ow:" Five days later , the last nine of my legs were out there , and I was wearing my mom &apos;s wife , and I was with him . <EOS> "
tw:" All this information is stored for at least six months , up to two years by your phone company or your Internet service provider . <EOS> "
ow:" All of these information are being done in the last four months , for two years , with the food that you &apos;re using , or you &apos;re building the company . <EOS> "
tw:" And now what she &apos;s looking at in New York are colleges , because she &apos;s determined to go to school in New York . <EOS> "
ow:" And now what &apos;s happening in New York is the college , because it has been working on the in the <EOS> "
tw:" I feel like it &apos;s easy to get caught up in the day-to-day , and forget what really matters to you . <EOS> "
ow:" I feel like it &apos;s easy to get the last two days , and the right thing is to do . <EOS> "
tw:" We have local numbers accessible to three quarters of a billion people on the planet . <EOS> "
ow:" We have the number of drugs that can be used to for the of . <EOS> "
tw:" There &apos;s another time when I put a garden in this homeless shelter in downtown Los Angeles . <EOS> "
ow:" There are some time I just met in a village in San Francisco . <EOS> "
tw:" This is where I live . I live in Kenya , at the south parts of the Nairobi National Park . <EOS> "
ow:" This is where I live . I live in the South Bronx <UNK> . <EOS> "
tw:" Our first project , the one that has inspired my first book , &quot; <UNK> from the <UNK> , &quot; was a project where we Italians decided to teach Zambian people how to grow food . <EOS> "
ow:" The first project , which led to my first book , &quot; The <UNK> <UNK> &quot; , &quot; a project that was the the to to to . . . . <EOS> "
Val Blue: 0.10273634210107328
epoch 26 : 452m 25s (- 490m 26s) (1000 47%) Loss: 3.0392
epoch 26 : 460m 16s (- 19m 19s) (2000 95%) Loss: 3.0990
epoch 26 : 460m 55s (- 0m 13s) (2083 99%) Loss: 3.0478
Computing VAL
Val loss: 5.851435375213623
tw:" I &apos;m still breaking the silence today . <EOS> "
ow:" I &apos;m the most optimistic . <EOS> "
tw:" And now what she &apos;s looking at in New York are colleges , because she &apos;s determined to go to school in New York . <EOS> "
ow:" And now what &apos;s happening in New York is the college , because it has been working on the in the <EOS> "
tw:" Not terribly damaged , but where the water had caused that <UNK> on the girl &apos;s face had to be repaired with such accuracy and delicacy . <EOS> "
ow:" There &apos;s no <UNK> , but it &apos;s still a the , , , , , , , , , , , , <EOS> "
tw:" This strange and awesome sight was like walking into ancient Egypt or Dante &apos;s <UNK> . <EOS> "
ow:" This kind of <UNK> thought is that in the U.S. the U.S. <UNK> <UNK> . <EOS> "
Val Blue: 0.10273634210107328
epoch 27 : 469m 21s (- 508m 47s) (1000 47%) Loss: 3.0716
epoch 27 : 477m 12s (- 20m 2s) (2000 95%) Loss: 3.0461
epoch 27 : 477m 51s (- 0m 13s) (2083 99%) Loss: 2.9867
Computing VAL
Val loss: 5.85143563747406
Epoch    27: reducing learning rate of group 0 to 2.5000e-09.
Epoch    27: reducing learning rate of group 0 to 2.5000e-09.
tw:" Eventually , after our long journey , my family and I were reunited in South Korea , but getting to freedom is only half the battle . <EOS> "
ow:" Finally , after a while I was in the hospital , and the family was born in Iraq , but also to the health of the disease as a family . <EOS> "
tw:" Now , I cannot deny that there have been some challenging moments in my family , moments where I &apos;ve wished that they were just like me . <EOS> "
ow:" Well , I can &apos;t even have a couple of times when I &apos;m in the , I I I , , , . <EOS> "
tw:" To me , Afghanistan is a country of hope and boundless possibilities , and every single day the girls of <UNK> remind me of that . <EOS> "
ow:" For me , the United States is a country , the , , , , , , , , , . <EOS> "
tw:" Can they really store all this information about us ? <EOS> "
ow:" Could they be able to connect our data ? <EOS> "
tw:" And I know there are people in the audience who are skeptical at this point , and maybe there are some fashionistas who are , like , &quot; Wait . Naomi . <UNK> . Joan <UNK> . Liu <UNK> . &quot; <EOS> "
ow:" I know that there are some people in your room who are doing this , and there are some of the &quot; &quot; the are , , &quot; , , , , , , . &quot; <EOS> "
tw:" But you have to maintain it . <EOS> "
ow:" But you have to look at it . <EOS> "
tw:" You have to create a new profession . <EOS> "
ow:" You have to create a new kind of new project . <EOS> "
Val Blue: 0.10273634210107328
epoch 28 : 486m 17s (- 527m 8s) (1000 47%) Loss: 3.0571
epoch 28 : 494m 8s (- 20m 45s) (2000 95%) Loss: 3.0906
epoch 28 : 494m 47s (- 0m 14s) (2083 99%) Loss: 3.1556
Computing VAL
Val loss: 5.851435279846191
tw:" When I was little , I thought my country was the best on the planet , and I grew up singing a song called &quot; Nothing To <UNK> . &quot; <EOS> "
ow:" When I was a kid , I think that the the the the the the the the the world , , &quot; , &quot; , &quot; , &quot; , &quot; we <EOS> "
tw:" He had just been really stressed out by the wedding and by becoming a family with me . <EOS> "
ow:" He was actually very , very , very , very , . . <EOS> "
tw:" I would like to talk to you about a very special group of animals . <EOS> "
ow:" I want to tell you about one of the groups groups . <EOS> "
tw:" So this neglected space became a constructive one , and people &apos;s hopes and dreams made me laugh out loud , tear up , and they <UNK> me during my own tough times . <EOS> "
ow:" So this space is a little bit of a space , and my and and my and and my my my my my , , , , and they me , <EOS> "
tw:" You have to go to the clinic to do it . It &apos;s very , very costly , and that means that , outside the clinical trials , it &apos;s just never done . It &apos;s never done . <EOS> "
ow:" You need to get to go to the to to do it . it &apos;s very , , , , , , , , , , to . . . . . . <EOS> "
tw:" My community , the Maasai , we believe that we came from heaven with all our animals and all the land for herding them , and that &apos;s why we value them so much . <EOS> "
ow:" My colleagues , our colleagues , our colleagues , we also come from the streets and all the way to stop it , and that &apos;s why we are so concerned about that . <EOS> "
Val Blue: 0.10273634210107328
epoch 29 : 503m 13s (- 545m 29s) (1000 47%) Loss: 3.0657
epoch 29 : 511m 4s (- 21m 27s) (2000 95%) Loss: 3.0366
epoch 29 : 511m 42s (- 0m 14s) (2083 99%) Loss: 3.0625
Computing VAL
Val loss: 5.85143551826477
tw:" One in three American women experiences domestic violence or stalking at some point in her life , and the CDC reports that 15 million children are abused every year , 15 million . <EOS> "
ow:" One third of the U.S. people in the United States and the are in the in a few decades , and they &apos;re , , , , , , , , , . <EOS> "
tw:" There was a big smile on his face which was unusual then , because the news mostly depressed him . <EOS> "
ow:" He was wearing a very , very , , , , he he he , he he . . . <EOS> "
tw:" And you can even see how I go from <UNK> by train to <UNK> , and how often I call in between . <EOS> "
ow:" You may have noticed that I went to a <UNK> store to the the , , , and , my I , my my <EOS> "
tw:" Thank you . <EOS> "
ow:" Thank you . <EOS> "
tw:" And then you have to tell them the truth about entrepreneurship . <EOS> "
ow:" And then you have to tell them the truth about politics . <EOS> "
Val Blue: 0.10273634210107328
epoch 30 : 520m 8s (- 563m 50s) (1000 47%) Loss: 3.0650
epoch 30 : 527m 59s (- 22m 10s) (2000 95%) Loss: 3.0711
epoch 30 : 528m 38s (- 0m 15s) (2083 99%) Loss: 3.0143
Computing VAL
Val loss: 5.851435375213623
tw:" The first time , I was driving to find a secret beach and I got lost , and he punched me in the side of my head so hard that the other side of my head repeatedly hit the driver &apos;s side window . <EOS> "
ow:" For the first time , I was just going to to to a a and and and and and and and and me my I my my my my my my <EOS> "
tw:" And she describes to me the feeling she felt as a five-year-old standing in that exact spot . <EOS> "
ow:" She explained to me that she was the last , , , was , <EOS> "
tw:" Thanks so much . Max Little , everybody . <EOS> "
ow:" Thank you very much . It &apos;s a <UNK> you can . <EOS> "
tw:" In a community of 10,000 people , we get 200 clients . <EOS> "
ow:" For a hundred million people , we have about three million people . <EOS> "
tw:" &quot; Oh , no , I cannot do this . &quot; &quot; Would you like me to find you somebody ? &quot; <EOS> "
ow:" &quot; Oh , no , I can &apos;t do this ? I can &apos;t tell you how many of you ? &quot; <EOS> "
tw:" They mix dye in these big barrels , and they submerge the silk into the liquid up to their elbows , but the dye is toxic . <EOS> "
ow:" They <UNK> the <UNK> into the big , and the and and the and , , , , , , , <EOS> "
tw:" They knew their image would be seen by you out in the world . <EOS> "
ow:" They know what they &apos;re going to look like in people , and they &apos;re <EOS> "
Val Blue: 0.10273634210107328
epoch 31 : 537m 4s (- 582m 11s) (1000 47%) Loss: 3.0568
epoch 31 : 544m 55s (- 22m 53s) (2000 95%) Loss: 3.0450
epoch 31 : 545m 34s (- 0m 15s) (2083 99%) Loss: 3.0871
Computing VAL
Val loss: 5.851435399055481
tw:" From time to time , the school would suddenly be canceled for a week because Taliban were suspicious . <EOS> "
ow:" There was a few time , the last was spent a week before the . <EOS> "
tw:" This is a blueprint how to survey your society , because you know who talks to whom , who sends whom an email , all this is possible if you have access to this information . <EOS> "
ow:" This is a way to develop the social media that you know that you , , , , , , , , , , , , you , , you . . <EOS> "
Val Blue: 0.10273634210107328
epoch 32 : 554m 0s (- 600m 32s) (1000 47%) Loss: 3.0714
epoch 32 : 561m 51s (- 23m 35s) (2000 95%) Loss: 3.0624
epoch 32 : 562m 30s (- 0m 16s) (2083 99%) Loss: 3.0938
Computing VAL
Val loss: 5.851435446739197
tw:" He looked at me <UNK> , but luckily he believed me . <EOS> "
ow:" He looked at me as a great , but was very surprising that my belief was . <EOS> "
tw:" The solution for that is to make roads out of porous asphalt . <EOS> "
ow:" The problem with the problem is that the the from <EOS> "
tw:" A real school . <EOS> "
ow:" One year was born . <EOS> "
tw:" My grandfather was an extraordinary man for his time . <EOS> "
ow:" My grandfather &apos;s a very is very , very <EOS> "
tw:" That &apos;s why I am a global ambassador for <UNK> , a global campaign to educate women . <EOS> "
ow:" So I &apos;m a global global engineer , which is a global economic for the first generation of women . <EOS> "
tw:" Did the <UNK> list and the <UNK> between female and male candidates bring peace and national reconciliation ? <EOS> "
ow:" Can the little <UNK> and the and and and and and and and and and the from the for <EOS> "
tw:" And the garden , it was beautiful . <EOS> "
ow:" And the top one , it &apos;s pretty beautiful . <EOS> "
tw:" So you got this scholarship . Yep . <EOS> "
ow:" So here he was born . <EOS> "
Val Blue: 0.10273634210107328
epoch 33 : 570m 55s (- 618m 53s) (1000 47%) Loss: 3.0635
epoch 33 : 578m 46s (- 24m 18s) (2000 95%) Loss: 3.0401
epoch 33 : 579m 25s (- 0m 16s) (2083 99%) Loss: 2.9433
Computing VAL
Val loss: 5.85143551826477
tw:" Due to <UNK> , due to <UNK> light , due to oxidation , this binder , this <UNK> , the glue between the aggregates is going to shrink , and if it shrinks , it gets <UNK> , and it <UNK> from the aggregates . <EOS> "
ow:" Using the quality of the environment , the light , the the , the , , , , , , , , , , , , , , , , , , , , , , the , , and the and the . the . . . . . "
tw:" This drug has now been banned for veterinary use in India , and they have taken a stand . <EOS> "
ow:" This was taken by the media in India in the West , and it was known as it was . <EOS> "
tw:" But then I said , I want to have this information , because this is my life you are <UNK> . <EOS> "
ow:" But then I said , I want to make a difference , because they &apos;re my own <EOS> "
tw:" So together with <UNK> Online and Open Data City , I did this . <EOS> "
ow:" So with the <UNK> and <UNK> <UNK> , I I . . <EOS> "
tw:" It &apos;s out of your control , and it &apos;s awesome , and it &apos;s not a career path . <EOS> "
ow:" It &apos;s the temperature of his car , and it &apos;s not a bad , but it &apos;s not a school . <EOS> "
tw:" No one knows what the hell we do . <EOS> "
ow:" Nobody knows what we &apos;re doing . <EOS> "
tw:" <UNK> is the most therapeutic and <UNK> act you can do , especially in the inner city . <EOS> "
ow:" The real goal is to have the best and the most that you can do , is <EOS> "
tw:" I had only one way out : the stairs from where I &apos;d come in . <EOS> "
ow:" There &apos;s a little bit of the I I . . <EOS> "
Val Blue: 0.10273634210107328
epoch 34 : 587m 51s (- 637m 13s) (1000 47%) Loss: 3.0594
epoch 34 : 595m 41s (- 25m 1s) (2000 95%) Loss: 3.0735
epoch 34 : 596m 20s (- 0m 17s) (2083 99%) Loss: 2.9417
Computing VAL
Val loss: 5.851435375213623
tw:" I also didn &apos;t know that the second step is to isolate the victim . <EOS> "
ow:" I don &apos;t know if the second is the number two . <EOS> "
tw:" So for the next five years , I dressed as a boy to <UNK> my older sister , who was no longer allowed to be outside alone , to a secret school . <EOS> "
ow:" For the last five years , I was , a guy who was I I I I , I , a I , I my my my my . . . <EOS> "
tw:" And I was scared . <EOS> "
ow:" I was so scared . <EOS> "
tw:" Not everybody gets to do that . <EOS> "
ow:" No one has to do that . <EOS> "
tw:" And I &apos;m insecure because I have to think about what I look like every day . <EOS> "
ow:" I was so surprised when I was doing my own work every day . <EOS> "
tw:" And that &apos;s how it looks to lions when they come at night . <EOS> "
ow:" And that &apos;s how the light that &apos;s in the the the the the the <EOS> "
tw:" You &apos;re working on other electrical inventions . <EOS> "
ow:" You &apos;re doing the right things to different . <EOS> "
tw:" You never arrive in a community with any ideas , and you sit with the local people . <EOS> "
ow:" Don &apos;t give you a community with the ideas , you sit in the house . <EOS> "
tw:" <UNK> way of maintaining things is not sustainable . <EOS> "
ow:" The <UNK> to the the are not <EOS> "
Val Blue: 0.10273634210107328
epoch 35 : 604m 46s (- 655m 35s) (1000 47%) Loss: 3.0805
epoch 35 : 612m 37s (- 25m 43s) (2000 95%) Loss: 3.0759
epoch 35 : 613m 16s (- 0m 17s) (2083 99%) Loss: 3.0151
Computing VAL
Val loss: 5.8514354705810545
tw:" They were lawyers , journalists , priests , they all said : &quot; We don &apos;t want this . &quot; <EOS> "
ow:" They &apos;re people who are , and they and , , , , &quot; they &quot; want &quot; to . <EOS> "
tw:" We see all the same symptoms . <EOS> "
ow:" We see them in the normal . <EOS> "
tw:" No need to go to the clinic for a routine <UNK> . <EOS> "
ow:" There &apos;s no need to get back to the . to . <EOS> "
tw:" <UNK> is the most therapeutic and <UNK> act you can do , especially in the inner city . <EOS> "
ow:" The real goal is to have the best and the most that you can do , is <EOS> "
tw:" If you want to meet with me , come to the garden with your shovel so we can plant some shit . <EOS> "
ow:" If you want to see me , go to the next side of your hand and we &apos;ll be able to add more . <EOS> "
tw:" As I looked through the photos , there were some were over a hundred years old , some still in the envelope from the processing lab , I couldn &apos;t help but think as a <UNK> that I could fix that tear and mend that scratch , and I knew hundreds of people who could do the same . <EOS> "
ow:" When I look at the pictures , some of them , some of them , I &apos;ve been in the of of my I , , I I , I , , , I , and I and I I and I I and I I and I and I "
Val Blue: 0.10273634210107328
epoch 36 : 621m 42s (- 673m 56s) (1000 47%) Loss: 3.0653
epoch 36 : 629m 33s (- 26m 26s) (2000 95%) Loss: 3.0883
epoch 36 : 630m 12s (- 0m 18s) (2083 99%) Loss: 3.0704
Computing VAL
Val loss: 5.8514354705810545
tw:" The journey by bus took one week , and we were almost caught several times . <EOS> "
ow:" The journey was taken by a little bit of a week , and we had a couple of years before we had lost our lives . <EOS> "
tw:" But I will do a trial . <EOS> "
ow:" But let me just show you . <EOS> "
tw:" I had no idea I was falling into crazy love , that I was walking headfirst into a carefully laid physical , financial and psychological trap . <EOS> "
ow:" I don &apos;t think I &apos;ve been in the &apos;t I &apos;m I , , , , , , and , , and . and . . . . . <EOS> "
tw:" Because there are no vultures , there &apos;s been a spread in the numbers of feral dogs at carcass dump sites , and when you have feral dogs , you have a huge time bomb of <UNK> . The number of cases of <UNK> has increased tremendously in India . <EOS> "
ow:" Because there &apos;s no <UNK> of the there &apos;s a of of the the the you , , , , , a you , , , a you , , , the , , , . the . the . the . . <EOS> "
tw:" I &apos;m rather here today to confess that we as a nation took the wrong choice , made the wrong decision . <EOS> "
ow:" And I &apos;m here to tell you that we have the countries that we don &apos;t , . . . . . . <EOS> "
tw:" L.A. leads the United States in vacant lots that the city actually owns . <EOS> "
ow:" The World Bank was the U.S. government of the Gulf of the city of the city . <EOS> "
tw:" <UNK> like her husband and her face , which otherwise would have been completely impossible to fix , we could just put them together in one good photo , and remake the whole photo . <EOS> "
ow:" If you don &apos;t know , like the man and the other , the guy , you can never them to be in a certain other , and , , . . . <EOS> "
tw:" When we first arrived , I went to have a quick look . <EOS> "
ow:" And I was going to the back , I went back to a <EOS> "
Val Blue: 0.10273634210107328
epoch 37 : 638m 38s (- 692m 17s) (1000 47%) Loss: 3.0784
epoch 37 : 646m 29s (- 27m 9s) (2000 95%) Loss: 3.0623
epoch 37 : 647m 8s (- 0m 18s) (2083 99%) Loss: 3.0206
Computing VAL
Val loss: 5.851435565948487
tw:" This was one of the lowest points in my life . <EOS> "
ow:" It was the worst moment of my life . <EOS> "
tw:" The solution for that is to make roads out of porous asphalt . <EOS> "
ow:" The problem with the problem is that the the from <EOS> "
tw:" I met <UNK> on a cold , rainy January night . <EOS> "
ow:" I met with a little girl in the , , and . . <EOS> "
tw:" Thank you very much . <EOS> "
ow:" Thank you very much . <EOS> "
tw:" Can they really store all this information about us ? <EOS> "
ow:" Could they be able to connect our data ? <EOS> "
tw:" This is the first outfit change on the TED stage , so you guys are pretty lucky to witness it , I think . <EOS> "
ow:" This is the first time that I was in the the this I , , , , . . . , <EOS> "
tw:" You just couldn &apos;t imagine how amazing a sunflower is and how it affects people . <EOS> "
ow:" You can &apos;t imagine that the the that these are and they the . <EOS> "
tw:" It could take an hour . It could take weeks . <EOS> "
ow:" It &apos;s not a long time . It &apos;s been <EOS> "
Val Blue: 0.10273634210107328
epoch 38 : 655m 34s (- 710m 38s) (1000 47%) Loss: 3.0655
epoch 38 : 663m 25s (- 27m 51s) (2000 95%) Loss: 3.0615
epoch 38 : 664m 4s (- 0m 19s) (2083 99%) Loss: 3.0088
Computing VAL
Val loss: 5.85143551826477
tw:" Then what you do is you heat up the steel , you melt the <UNK> , and the <UNK> will flow into these <UNK> , and the stones are again fixed to the surface . <EOS> "
ow:" What you do is you take a <UNK> , you to to to and and and and and and and and , , , , , , , the . <EOS> "
tw:" So a microwave is a similar system . <EOS> "
ow:" The <UNK> are also very complex . <EOS> "
tw:" And if you don &apos;t believe me , ask your phone company what information they store about you . <EOS> "
ow:" And if you don &apos;t believe me , you give the patient to help them understand . <EOS> "
tw:" Unfortunately after you &apos;ve gone to school , and you have a résumé and you &apos;ve done a few jobs , you can &apos;t say anything anymore , so if you say you want to be the President of the United States , but your résumé reads , &quot; <UNK> Model : 10 years , &quot; people give you a funny look . <EOS> "
ow:" It &apos;s so long after he &apos;s going to , and , , , , , , , , , , , , , , , , , you , , &quot; , &quot; , &quot; , &quot; , , , , , , , , , , , , "
tw:" The city has some of the most beautiful architecture in the world , but it also has one of the highest amounts of abandoned properties in America . <EOS> "
ow:" The world has a huge number of the largest largest in the world , but it &apos;s also a huge number of great leaders in the United States . <EOS> "
tw:" But we &apos;ll get a very large sample of data that is collected from all different circumstances , and it &apos;s getting it in different circumstances that matter because then we are looking at ironing out the confounding factors , and looking for the actual markers of the disease . <EOS> "
ow:" But we &apos;ll take a bunch of data that we &apos;ve all been together , and we &apos;ve , in , in the , , , , , , , , , , , and , , and , and , and , and . <EOS> "
tw:" Local , passionate people . That &apos;s who you have <UNK> . <EOS> "
ow:" The man , the people who , the . . . . . <EOS> "
tw:" And in <UNK> , this group of people came together , and they all speculated about what would happen to the city of New York in 100 years , and the conclusion was <UNK> : The city of New York would not exist in 100 years . <EOS> "
ow:" And in the 1930s , the group of the , , , and , the , , , and , and , and , the New New York , , , the , New York is , , . <EOS> "
tw:" At the end of my first week there , I found myself helping out in an evacuation center in the town . <EOS> "
ow:" In the first day I was , I was trying to build a building in India . <EOS> "
tw:" You don &apos;t get a chance to mess it up . <EOS> "
ow:" You don &apos;t have a chance to have to have a <EOS> "
Val Blue: 0.10273634210107328
epoch 39 : 672m 30s (- 728m 59s) (1000 47%) Loss: 3.0717
epoch 39 : 680m 21s (- 28m 34s) (2000 95%) Loss: 3.0381
epoch 39 : 681m 0s (- 0m 19s) (2083 99%) Loss: 2.9919
Computing VAL
Val loss: 5.851435422897339
tw:" He &apos;s not greedy . He doesn &apos;t see skin color . <EOS> "
ow:" She &apos;s not . . . . . <EOS> "
tw:" And when we do this , who knows ? <EOS> "
ow:" And when we do that , what do you know ? <EOS> "
tw:" The <UNK> are the warriors who protect our community and the livestock , and they &apos;re also upset about this problem . <EOS> "
ow:" The <UNK> <UNK> and <UNK> and and and and , the , , . . <EOS> "
tw:" So I got an old car battery , an indicator box . It &apos;s a small device found in a motorcycle , and it helps motorists when they want to turn right or left . It blinks . <EOS> "
ow:" So I took a <UNK> of the the the the a the the the a the the the the a . of , , , , , , , , , , , , , , , , , , , , , , , , it , it , "
tw:" Thank you . <EOS> "
ow:" Thank you . <EOS> "
tw:" Children are taken from their families and trafficked and vanished , and they &apos;re forced to work endless hours on these boats on the lake , even though they do not know how to swim . <EOS> "
ow:" The kids are coming in their family , and they &apos;re and they and , and , and , and , and , , , , . , . . . <EOS> "
Val Blue: 0.10273634210107328
epoch 40 : 689m 26s (- 747m 20s) (1000 47%) Loss: 3.0487
epoch 40 : 697m 16s (- 29m 17s) (2000 95%) Loss: 3.0544
epoch 40 : 697m 55s (- 0m 20s) (2083 99%) Loss: 2.9951
Computing VAL
Val loss: 5.851435327529908
tw:" One of the smartest things <UNK> did , from the very beginning , was to create the illusion that I was the dominant partner in the relationship . <EOS> "
ow:" One of the most amazing things that happen , the beginning of the beginning , is to create a form that I &apos;m a <EOS> "
tw:" And he was very , very sorry . <EOS> "
ow:" And he was very <UNK> . <EOS> "
tw:" They are very graceful . Charles Darwin said he changed his mind because he watched them fly effortlessly without energy in the skies . <EOS> "
ow:" They &apos;re very young . They &apos;re told that the change she &apos;s , , , , , , , , , she , she . <EOS> "
tw:" Eventually , after a period of six months of brutal war and a toll rate of almost 50,000 dead , we managed to liberate our country and to topple the tyrant . <EOS> "
ow:" And then , after 9 / 11 , we had a <UNK> , and we we , and we , , and and the and . . . . <EOS> "
tw:" You &apos;d be surprised what the soil could do if you let it be your canvas . <EOS> "
ow:" You will be aware of what the Internet can do if you make them with the kids . <EOS> "
tw:" A conservative estimate tells us there are more than 27 million people enslaved in the world today . <EOS> "
ow:" A <UNK> <UNK> that we &apos;ve been hearing many of the million million people who are <EOS> "
Val Blue: 0.10273634210107328
epoch 41 : 706m 21s (- 765m 41s) (1000 47%) Loss: 3.0440
epoch 41 : 714m 12s (- 29m 59s) (2000 95%) Loss: 3.0732
epoch 41 : 714m 51s (- 0m 20s) (2083 99%) Loss: 3.0243
Computing VAL
Val loss: 5.85143551826477
tw:" <UNK> thousand eight hundred thirty lines of information . <EOS> "
ow:" <UNK> the whole data . <EOS> "
tw:" Because while we take the same photo , our perspectives change , and she reaches new <UNK> , and I get to see life through her eyes , and how she interacts with and sees everything . <EOS> "
ow:" Because we had just been a picture of the , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , . . <EOS> "
tw:" And I got these free things because of how I look , not who I am , and there are people paying a cost for how they look and not who they are . <EOS> "
ow:" I had the right to be in my my my my my my my my I , not my , , and and , , , , , , they me they . . <EOS> "
tw:" It was cool , and they just shared the stories about how this affected them and how they used to plant with their mother and their grandmother , and it was just cool to see how this changed them , if it was only for that one moment . <EOS> "
ow:" It &apos;s very , very good at the , and they , and , and , and , and , and , and , and , and , and , and , and , and , and it was , . , . <EOS> "
tw:" But I know electric fences are already invented , but I want to make mine . <EOS> "
ow:" You know , the <UNK> is still , and he wanted to . <EOS> "
tw:" Thank you . <EOS> "
ow:" Thank you . <EOS> "
tw:" As they had run from the wave , and for their lives , absolutely everything they had , everything had to be left behind . <EOS> "
ow:" When the <UNK> came out , they went to the local , they were all the same , all the other things that were . <EOS> "
Val Blue: 0.10273634210107328
epoch 42 : 723m 17s (- 784m 3s) (1000 47%) Loss: 3.0535
epoch 42 : 731m 8s (- 30m 42s) (2000 95%) Loss: 3.0538
epoch 42 : 731m 47s (- 0m 21s) (2083 99%) Loss: 3.0857
Computing VAL
Val loss: 5.851435232162475
tw:" Porous asphalt , a material that we use now in most of the highways in the Netherlands , it has pores and water can just rain through it , so all the rainwater will flow away to the sides , and you have a road that &apos;s easy to drive on , so no splash water anymore . <EOS> "
ow:" <UNK> is the kind of material that we &apos;re using , and we , , , to , , , , , , , the , , and the , , , , , , , , , , , and and and , to a and , a to "
tw:" It was on a strip of land that we call a <UNK> . <EOS> "
ow:" It &apos;s on a map of the Earth that we call the &quot; <UNK> . &quot; <EOS> "
tw:" And when we do this , who knows ? <EOS> "
ow:" And when we do that , what do you know ? <EOS> "
tw:" So I put the lights . You can see at the back , those are the lion lights . <EOS> "
ow:" So I &apos;ve taken the color . You can see it in the sky , the the . . <EOS> "
Val Blue: 0.10273634210107328
epoch 43 : 740m 13s (- 802m 24s) (1000 47%) Loss: 3.0869
epoch 43 : 748m 4s (- 31m 25s) (2000 95%) Loss: 3.0620
epoch 43 : 748m 43s (- 0m 21s) (2083 99%) Loss: 3.0811
Computing VAL
Val loss: 5.851435494422913
tw:" I was so shocked . <EOS> "
ow:" I was born . <EOS> "
tw:" I also didn &apos;t know that the second step is to isolate the victim . <EOS> "
ow:" I don &apos;t know if the second is the number two . <EOS> "
tw:" I want to challenge that . Do you know why ? <EOS> "
ow:" I want to leave you with what you know ? <EOS> "
tw:" But these great conversations can &apos;t occur if our scientists and engineers don &apos;t invite us in to see their <UNK> . <EOS> "
ow:" But the unexpected thing about not even the science and the <UNK> have never said it on the street . <EOS> "
tw:" I made this last year , and started receiving hundreds of messages from passionate people who wanted to make a wall with their community , so my civic center colleagues and I made a tool kit , and now walls have been made in countries around the world , including Kazakhstan , South Africa , Australia , Argentina and beyond . <EOS> "
ow:" I &apos;ve been doing this project , and I started to collect hundreds of thousands of people who were doing this in their own community , and the and , , , , , , I , , and , the . the . . <EOS> "
tw:" We couldn &apos;t <UNK> the photo unless it was cleaned , dry and reclaimed . <EOS> "
ow:" We couldn &apos;t get the idea of the if it didn &apos;t get , and the and . . . . <EOS> "
Val Blue: 0.10273634210107328
epoch 44 : 757m 9s (- 820m 45s) (1000 47%) Loss: 3.0741
epoch 44 : 765m 0s (- 32m 7s) (2000 95%) Loss: 3.0522
epoch 44 : 765m 39s (- 0m 22s) (2083 99%) Loss: 2.9868
Computing VAL
Val loss: 5.851435327529908
tw:" Our society , shaped by a revolutionary mindset , became more polarized and has driven away from the ideals and the principles -- freedom , dignity , social justice -- that we first held . <EOS> "
ow:" Our lives , our <UNK> , are the , , , and , , and and , , , , , , , , , , , , , . our . our . <EOS> "
Val Blue: 0.10273634210107328
epoch 45 : 774m 5s (- 839m 6s) (1000 47%) Loss: 3.0816
epoch 45 : 781m 56s (- 32m 50s) (2000 95%) Loss: 3.0465
epoch 45 : 782m 34s (- 0m 22s) (2083 99%) Loss: 3.0964
Computing VAL
Val loss: 5.851435256004334
tw:" So we took a lot of samples from this road and we tested them in the lab . <EOS> "
ow:" We &apos;ve taken a lot of these from this , and we we them them in the lab . <EOS> "
tw:" And he was very , very sorry . <EOS> "
ow:" And he was very <UNK> . <EOS> "
tw:" &quot; <UNK> me now , if you wish , &quot; he said , &quot; but I will not ruin my daughter &apos;s future because of your old and backward ideas . &quot; <EOS> "
ow:" He said , &quot; If I want to kill me , I &apos;m going to have my heart to the future of my parents , because the and and and and the . . . <EOS> "
tw:" Which presentation have you <UNK> the most this morning ? <EOS> "
ow:" How much would you have a great deal of this ? <EOS> "
Val Blue: 0.10273634210107328
epoch 46 : 791m 1s (- 857m 27s) (1000 47%) Loss: 3.0522
epoch 46 : 798m 51s (- 33m 33s) (2000 95%) Loss: 3.0267
epoch 46 : 799m 30s (- 0m 23s) (2083 99%) Loss: 3.0219
Computing VAL
Val loss: 5.851435303688049
tw:" He &apos;s speechless , but he communicates joy in a way that some of the best <UNK> cannot . <EOS> "
ow:" You don &apos;t say , but you have to feel that you can see the the that you you can , the only the . <EOS> "
tw:" But most people don &apos;t agree . <EOS> "
ow:" But most people don &apos;t agree . <EOS> "
tw:" The real way that I became a model is I won a genetic lottery , and I am the recipient of a legacy , and maybe you &apos;re wondering what is a legacy . <EOS> "
ow:" I actually became the because I was playing the music , and I was the only person who was in the art , and you could be able to tell the . <EOS> "
tw:" Cabin restaurants , as they &apos;re known in the trade , are venues for forced prostitution . <EOS> "
ow:" The <UNK> , the , , , , , , , the . . <EOS> "
Val Blue: 0.10273634210107328
epoch 47 : 807m 56s (- 875m 48s) (1000 47%) Loss: 3.0828
epoch 47 : 815m 47s (- 34m 15s) (2000 95%) Loss: 3.0550
epoch 47 : 816m 26s (- 0m 23s) (2083 99%) Loss: 3.0102
Computing VAL
Val loss: 5.85143563747406
tw:" He needed them to feel protected . <EOS> "
ow:" He needs to be able to feel like they &apos;re going to be <EOS> "
tw:" It was 7 a.m. I still had on my <UNK> . <EOS> "
ow:" That was when I was in the morning when I was still a little girl . <EOS> "
tw:" In Hindu mythology , <UNK> was the vulture god , and he risked his life in order to save the goddess <UNK> from the <UNK> <UNK> <UNK> . <EOS> "
ow:" In the <UNK> , <UNK> <UNK> , <UNK> , <UNK> , <UNK> <UNK> , the the the the the the the the . . . <EOS> "
tw:" With a mobile phone , you can shoot a crime against humanity in Syria . <EOS> "
ow:" With a mobile phone , you can actually put the image of the <UNK> in the in . <EOS> "
tw:" However , Gaddafi left behind a heavy burden , a legacy of tyranny , corruption and seeds of <UNK> . <EOS> "
ow:" However , the police gave a new , a <UNK> , , , , , and the . . . <EOS> "
tw:" What I &apos;m talking about is putting people to work , and getting kids off the street , and letting them know the joy , the pride and the honor in growing your own food , opening farmer &apos;s markets . <EOS> "
ow:" I &apos;m talking about how to do that , and the kids and the and and , , , , , , , and , and and and and and and and and and and and and and and and and and <EOS> "
tw:" It &apos;s a small fishing town in <UNK> <UNK> , about 50,000 people , one of the first that was hit by the wave . <EOS> "
ow:" It &apos;s a small village that &apos;s a <UNK> , , , , , , , , , , . the . the . <EOS> "
Val Blue: 0.10273634210107328
epoch 48 : 824m 52s (- 894m 9s) (1000 47%) Loss: 3.0768
epoch 48 : 832m 43s (- 34m 58s) (2000 95%) Loss: 3.0700
epoch 48 : 833m 22s (- 0m 24s) (2083 99%) Loss: 2.8996
Computing VAL
Val loss: 5.851435351371765
tw:" At that moment , I heard one man &apos;s voice ask me , &quot; What &apos;s wrong ? &quot; <EOS> "
ow:" Now , there &apos;s a couple of girls saying , &quot; What &apos;s wrong ? &quot; <EOS> "
tw:" Unfortunately after you &apos;ve gone to school , and you have a résumé and you &apos;ve done a few jobs , you can &apos;t say anything anymore , so if you say you want to be the President of the United States , but your résumé reads , &quot; <UNK> Model : 10 years , &quot; people give you a funny look . <EOS> "
ow:" It &apos;s so long after he &apos;s going to , and , , , , , , , , , , , , , , , , , you , , &quot; , &quot; , &quot; , &quot; , , , , , , , , , , , , "
tw:" Two of the most valuable things we have are time and our relationships with other people . <EOS> "
ow:" The second thing we all have is , and think about other people &apos;s minds . <EOS> "
tw:" You should see the rubbish — -- You should see the rubbish that we have <UNK> on unsuspecting African people . <EOS> "
ow:" You can look at the -- -- you know , the , , , , , , , , , , , the . . . <EOS> "
tw:" It was very time-consuming . <EOS> "
ow:" It &apos;s too long . <EOS> "
tw:" Sex trafficking is what we often think of when we hear the word slavery , and because of this worldwide awareness , I was warned that it would be difficult for me to work safely within this particular industry . <EOS> "
ow:" We think of love as a child , as a result of that , and I think , is to be , to , to , , , , , the <EOS> "
Val Blue: 0.10273634210107328
epoch 49 : 841m 48s (- 912m 31s) (1000 47%) Loss: 3.0422
epoch 49 : 849m 39s (- 35m 41s) (2000 95%) Loss: 3.0847
epoch 49 : 850m 18s (- 0m 24s) (2083 99%) Loss: 2.9417
Computing VAL
Val loss: 5.851435351371765
tw:" It manifests in each individual differently , hence why <UNK> is so different from Sam . <EOS> "
ow:" The money in the other , the , , , , , , , , . . <EOS> "
tw:" I want to challenge that . Do you know why ? <EOS> "
ow:" I want to leave you with what you know ? <EOS> "
tw:" Here you can see how hundreds of thousands of people stood up and protested for change . <EOS> "
ow:" You can see here that people with thousands of people who have been and <EOS> "
tw:" Local , passionate people . That &apos;s who you have <UNK> . <EOS> "
ow:" The man , the people who , the . . . . . <EOS> "
tw:" The big sheets of slate were heavier than the children carrying them , and the kids hoisted them from their heads using these handmade harnesses of sticks and rope and torn cloth . <EOS> "
ow:" The small ones were getting more than the children , and they were they , and they , , , , they <EOS> "
Val Blue: 0.10273634210107328
epoch 50 : 858m 44s (- 930m 52s) (1000 47%) Loss: 3.0719
epoch 50 : 866m 34s (- 36m 23s) (2000 95%) Loss: 3.0317
epoch 50 : 867m 13s (- 0m 24s) (2083 99%) Loss: 3.0378
Computing VAL
Val loss: 5.851435613632202
tw:" When I was little , I thought my country was the best on the planet , and I grew up singing a song called &quot; Nothing To <UNK> . &quot; <EOS> "
ow:" When I was a kid , I think that the the the the the the the the the world , , &quot; , &quot; , &quot; , &quot; , &quot; we <EOS> "
tw:" &quot; I &apos;m not helping you , &quot; he said . <EOS> "
ow:" &quot; I don &apos;t want to say , &quot; I read . <EOS> "
tw:" But I will do a trial . <EOS> "
ow:" But let me just show you . <EOS> "
tw:" And here &apos;s where those guns come in . <EOS> "
ow:" And then , on the top of the back . <EOS> "
tw:" I was working on my computer trying to finish a freelance writing assignment , and I got frustrated , and <UNK> used my anger as an excuse to put both of his hands around my neck and to squeeze so tightly that I could not breathe or scream , and he used the <UNK> to hit my head repeatedly against the wall . <EOS> "
ow:" I &apos;m wearing a <UNK> , and , , and , and , and , , , , , , , , , , , , , , , , , , , , , , , , , , , , the of and . and . and . "
tw:" To me , this is the saddest and most painful question that people ask , because we victims know something you usually don &apos;t : It &apos;s incredibly dangerous to leave an <UNK> . <EOS> "
ow:" For me , it &apos;s a good question , and , of course , , and , , , , , , , of you , you &apos;t . . . <EOS> "
tw:" This is a blueprint for countries like China and Iran . <EOS> "
ow:" This is a design that &apos;s been for the the as the <EOS> "
tw:" So these photos are far more than <UNK> for a single moment , or even a specific trip . <EOS> "
ow:" These pictures are not just the only ones that are the , , a , a . . <EOS> "
tw:" And I &apos;m like , &quot; Come on , really ? <EOS> "
ow:" And I thought , &quot; Okay , what is that ? &quot; <EOS> "
tw:" We have helped to start 40,000 businesses . <EOS> "
ow:" We &apos;ve tried to build a <UNK> . . <EOS> "
tw:" When I was working in the field , I brought lots of candles with me , and with the help of my interpreter , I imparted to the people I was photographing that I wanted to illuminate their stories and their plight , so when it was safe for them , and safe for me , I made these images . <EOS> "
ow:" When I work in this field , I went to a lot of pain , and I was able to share with people I read that I was in the writing , and I was able to go and I and I and I and I and I and I "
Val Blue: 0.10273634210107328
epoch 51 : 875m 40s (- 949m 13s) (1000 47%) Loss: 3.1025
epoch 51 : 883m 31s (- 37m 6s) (2000 95%) Loss: 3.0697
epoch 51 : 884m 9s (- 0m 25s) (2083 99%) Loss: 3.0600
Computing VAL
Val loss: 5.851435375213623
tw:" Several times we can repeat that . <EOS> "
ow:" We can do it again for a long time . <EOS> "
tw:" But you can see how your people are communicating with each other , what times they call each other , when they go to bed . <EOS> "
ow:" But you can see how we interact with each other , they &apos;re going to play all the time , when they die . <EOS> "
tw:" I am here today not at all to inspire you with our success story of the <UNK> list and the elections . <EOS> "
ow:" I &apos;m here to have to tell you about the story of a study and a and and and a . . . . . <EOS> "
tw:" So if the photographer is right there and the light is right there , like a nice <UNK> , and the client says , &quot; Cameron , we want a walking shot , &quot; well then this leg goes first , nice and long , this arm goes back , this arm goes forward , the head is at three quarters , and you just go back and forth , just do that , and then you look back at your imaginary friends , 300 , 400 , 500 times . <EOS> "
ow:" If the British man is here , the same thing is a very simple , and , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , "
tw:" Here &apos;s me on the soccer team and in V Magazine . <EOS> "
ow:" This is me with the <UNK> in the . <EOS> "
tw:" We gotta flip the script on what a gangsta is . <EOS> "
ow:" We &apos;re going to change the concept of the . <EOS> "
tw:" Wrong . They were all enslaved . <EOS> "
ow:" <UNK> . They &apos;re all . <EOS> "
Val Blue: 0.10273634210107328
epoch 52 : 892m 36s (- 967m 35s) (1000 47%) Loss: 3.0848
epoch 52 : 900m 26s (- 37m 49s) (2000 95%) Loss: 3.0279
epoch 52 : 901m 5s (- 0m 25s) (2083 99%) Loss: 2.9551
Computing VAL
Val loss: 5.8514354705810545
tw:" It &apos;s almost impossible to cross the border between North Korea and South Korea , so , ironically , I took a flight back to China and I headed toward the North Korean border . <EOS> "
ow:" Because it &apos;s about the from the North Pole to San Francisco , it &apos;s not possible , I &apos;m not going to go to China and go to the bottom of the North Pole . <EOS> "
tw:" We victims need everyone . <EOS> "
ow:" We &apos;re going to need everyone to all of us . <EOS> "
tw:" There are 10,000 species of birds in the world . <EOS> "
ow:" There are now about a million of them in the world . <EOS> "
tw:" And this information is stored for at least six months in Europe , up to two years . <EOS> "
ow:" And this whole thing is in the in the last two , , , , , <EOS> "
tw:" Take your science , subtract your bullet points and your jargon , divide by relevance , meaning share what &apos;s relevant to the audience , and multiply it by the passion that you have for this incredible work that you &apos;re doing , and that is going to equal incredible interactions that are full of understanding . <EOS> "
ow:" So , for &quot; <UNK> &quot; with the &quot; &quot; and &quot; and &quot; , , , , , , , , , , , , , , , , , , , , , , , to , , , , , . &quot; <EOS> "
tw:" but &quot; How many times will I get stopped ? When will I get stopped ? &quot; <EOS> "
ow:" What is it that I &apos;m going to live and be in ? &quot; <EOS> "
tw:" But <UNK> , with Parkinson &apos;s disease and other movement disorders , there are no <UNK> , so there &apos;s no simple blood test that you can do , and the best that we have is like this 20-minute neurologist test . <EOS> "
ow:" But it &apos;s also a <UNK> , and , , , , , , , , , , , , , , , and , , , , and , , , the you , . and the . and . . . . <EOS> "
tw:" What are you going to get out of those samples ? <EOS> "
ow:" What are you going to do about these kinds of ? <EOS> "
tw:" After we finished talking , I felt so horrible and honestly ashamed at my own lack of knowledge of this <UNK> in my own lifetime , and I thought , if I don &apos;t know , how many other people don &apos;t know ? <EOS> "
ow:" And after the end of the story , I was so excited and really , really , really , really , really , really , really , really , really , really , ? <EOS> "
Val Blue: 0.10273634210107328
epoch 53 : 909m 32s (- 985m 56s) (1000 47%) Loss: 3.0397
epoch 53 : 917m 23s (- 38m 31s) (2000 95%) Loss: 3.0812
epoch 53 : 918m 1s (- 0m 26s) (2083 99%) Loss: 3.0285
Computing VAL
Val loss: 5.851435256004334
tw:" He had these big cheeks , these big apple cheeks and this <UNK> hair , and he seemed so sweet . <EOS> "
ow:" He had this big , little <UNK> , and he and he and he and and and and and and , he , . . . . <EOS> "
tw:" The answer is easy . <EOS> "
ow:" The answer is very simple . <EOS> "
tw:" <UNK> could be affecting your daughter , your sister , your best friend right now . <EOS> "
ow:" The ability to make your friends , your children , your friends , your best example . <EOS> "
tw:" No need to go to the clinic for a routine <UNK> . <EOS> "
ow:" There &apos;s no need to get back to the . to . <EOS> "
tw:" There &apos;s only one thing that all the successful companies in the world have in common , only one : None were started by one person . <EOS> "
ow:" There &apos;s one thing that people have done in the world that &apos;s just a , , , a , , a , a . . . . <EOS> "
Val Blue: 0.10273634210107328
epoch 54 : 926m 41s (- 1004m 31s) (1000 47%) Loss: 3.0393
epoch 54 : 934m 49s (- 39m 15s) (2000 95%) Loss: 3.0873
epoch 54 : 935m 29s (- 0m 26s) (2083 99%) Loss: 3.0323
Computing VAL
Val loss: 5.8514354705810545
tw:" When you see a vulture like this , the first thing that comes to your mind is , these are disgusting , ugly , greedy creatures that are just after your flesh , associated with politicians . <EOS> "
ow:" When you see a <UNK> , this is the the the the , , the , , , , , , , , , , , , , , , , , , . . <EOS> "
tw:" I would want to quit , but my father , he would say , &quot; Listen , my daughter , you can lose everything you own in your life . <EOS> "
ow:" I &apos;m really happy to say , &quot; Oh , my son , he &apos;s going to say , &quot; You can , you can . &quot; <EOS> "
tw:" Hold it up . <EOS> "
ow:" Please raise it . <EOS> "
tw:" So together with <UNK> Online and Open Data City , I did this . <EOS> "
ow:" So with the <UNK> and <UNK> <UNK> , I I . . <EOS> "
tw:" A few things to consider are having examples , stories and analogies . Those are ways to engage and excite us about your content . <EOS> "
ow:" So the idea of the question , the , , , is that the and and that to and and , and , and , and . . . <EOS> "
Val Blue: 0.10273634210107328
epoch 55 : 944m 13s (- 1023m 32s) (1000 47%) Loss: 3.0341
epoch 55 : 952m 21s (- 39m 59s) (2000 95%) Loss: 3.0598
epoch 55 : 953m 2s (- 0m 27s) (2083 99%) Loss: 2.9140
Computing VAL
Val loss: 5.851435399055481
tw:" Because MPs do not keep the environment clean . <EOS> "
ow:" Because the price is not going to the . <EOS> "
tw:" The fall of the Berlin Wall would maybe not &#91; have been &#93; there . <EOS> "
ow:" The National Union of the ocean will probably not exist . <EOS> "
tw:" However , there are <UNK> million people worldwide who have the disease , and they have to live with incurable weakness , tremor , rigidity and the other symptoms that go along with the disease , so what we need are objective tools to detect the disease before it &apos;s too late . <EOS> "
ow:" However , the million million people in the , the , and , , , , , , , , , , , , and , , , , , , , , , , , , the that . the to , , to the . . . <EOS> "
tw:" Plus you get strawberries . <EOS> "
ow:" You know , you get the whole number of water . <EOS> "
Val Blue: 0.10273634210107328
epoch 56 : 961m 46s (- 1042m 33s) (1000 47%) Loss: 3.0594
epoch 56 : 969m 54s (- 40m 44s) (2000 95%) Loss: 3.0565
epoch 56 : 970m 34s (- 0m 27s) (2083 99%) Loss: 3.0337
Computing VAL
Val loss: 5.851435399055481
tw:" So I was living in constant fear that my identity could be revealed , and I would be <UNK> to a horrible fate back in North Korea . <EOS> "
ow:" I still live in a strange fear of what I believe to be , and I &apos;m going to share the lives of the in the in <EOS> "
tw:" Over 70 percent of domestic violence murders happen after the victim has ended the relationship , after she &apos;s gotten out , because then the <UNK> has nothing left to lose . <EOS> "
ow:" Over the 50 percent of the time that the children the day , the , , , , , , , , , , , , . <EOS> "
tw:" It &apos;s not to say that our mothers aren &apos;t key in our success . <EOS> "
ow:" This is not saying that God is not in our own business . <EOS> "
tw:" But then after a while I realized , this is my life . <EOS> "
ow:" But then I realized , this is my life . <EOS> "
tw:" We &apos;re going to cheer you on every step of the way , my friend . <EOS> "
ow:" We &apos;re going to take the your back , and you . . . . <EOS> "
tw:" &quot; As I worked , I couldn &apos;t help but think about the individuals and the stories represented in the images . <EOS> "
ow:" &quot; I don &apos;t mean , I don &apos;t think about the rest of the people and the other stories . <EOS> "
tw:" <UNK> exists everywhere , nearly , in the world , and yet it is illegal everywhere in the world . <EOS> "
ow:" The very , the the that the in the world , , , it , <EOS> "
Val Blue: 0.10273634210107328
slurmstepd: error: *** JOB 10843937 ON gpu-68 CANCELLED AT 2018-12-14T00:07:58 ***
